version: "3"

services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      # The HTTP port
      - "${EXTERNAL_IP:-0.0.0.0}:80:80"
      # The HTTPS port
      - "${EXTERNAL_IP:-0.0.0.0}:443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "${INTERNAL_IP:-127.0.0.1}:${INTERNAL_PORT:-8080}:8080"
    volumes:
      # Traefik configuration file
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./conf.d:/etc/traefik/conf.d
      - ./acme:/etc/traefik/acme
      # So that Traefik can listen to the Docker events
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    networks:
      - traefik
    restart: unless-stopped
  cert-exporter:
    image: ldez/traefik-certs-dumper:v2.8.1
    entrypoint: |
      traefik-certs-dumper file --version v2 --watch
      --source /data/acme.json --dest /data/exported
    volumes:
      - ./acme:/data
    depends_on:
      - reverse-proxy
    restart: unless-stopped

networks:
  traefik:
    # Use this network in other docker-compose projects
    name: traefik_overlay
